[tool.poetry]
name = "titans"
version = "0.1.0"
description = ""
authors = ["Fonz <fonz@botverse.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.5.1"
datasets = "^3.2.0"
transformers = "^4.48.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
